/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Aux.Dialog;
import Classes.Categoria;
import Classes.Empresa;
import Classes.Entitat;
import Classes.LlistaCategories;
import Classes.LlistaEntitats;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumne
 */
public class IncidenciaModificarObjecte extends javax.swing.JFrame {

    public static int type; //0 categories //1 entitats
    public static int id, idC, idE;
    public static String t, d, u;
    /**
     * Creates new form IncidenciaModificarObjecte
     */
    public IncidenciaModificarObjecte(int type, int id, String topic, String description, int idC, String user, int idE) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.type = type;
        this.id = id;
        this.t = topic;
        this.d = description;
        this.idC = idC;
        this.u = user;
        this.idE = idE;
        emplenarTaula();
   }

    private IncidenciaModificarObjecte() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tornar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sel·lecionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IncidenciesModificar i = new IncidenciesModificar(id, t, d, idC, u, idE);
        i.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int s = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            if(type == 0){
                IncidenciesModificar i = new IncidenciesModificar(id, t, d, s, u, idE);
                i.setVisible(true);
                dispose();
            } else {
                IncidenciesModificar i = new IncidenciesModificar(id, t, d, idC, u, s);
                i.setVisible(true);
                dispose();                
            }
        } catch(Exception e){
            Dialog.dialog("Sel·leciona un element.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncidenciaModificarObjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncidenciaModificarObjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncidenciaModificarObjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncidenciaModificarObjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IncidenciaModificarObjecte().setVisible(true);
        });
    }
    public void emplenarTaula() {
        if(type == 1){
            Object columnNames[] = {"ID", "Nom", "Codi", "Contacte", "Estat", "Tipus"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            for (int i = 0; i < LlistaEntitats.llistaEntitat.size(); i++) {

                Entitat e = LlistaEntitats.returnList().get(i);
                if(e instanceof Empresa){
                    Object rowData[] = {e.getId(), e.getName(), e.getCode(), e.getContact(), e.getStatus(), "Empresa"};
                    model.addRow(rowData);
                }else{
                    Object rowData[] = {e.getId(), e.getName(), e.getCode(), e.getContact(), e.getStatus(), "Institut"};
                    model.addRow(rowData);  
                }
            }
            jTable1.setModel(model);
        } else {
            Object columnNames[] = {"ID", "Nom", "Descripció", "Estat"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (int i = 0; i < LlistaCategories.llistaCategoria.size(); i++) {

            Categoria e = LlistaCategories.returnList().get(i);
                Object rowData[] = {e.getId(), e.getName(), e.getDescription(), e.getStatus()};
                model.addRow(rowData);  
        }
        jTable1.setModel(model);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
