package JFrame;

import Classes.*;
import static Classes.Categoria.getNumeroTags;
import static JFrame.TagsConsulta.li;
import java.util.ListIterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Length;

/**
 * 
 * Programa per gestionar les categories
 * 04/02/2020
 * @author svyatossemenyuk
 * GRUP 1: Xavi Naves - Xavier Romeu - Javier Perez - Svyatos Semenyuk
 * @version v5 (versio final, amb CRUD, CSV import/export, Logs, ArrayList tot)
 */

public class TagsElimina extends javax.swing.JFrame {

    public TagsElimina() {
        initComponents();
        emplenarTaula();
        
        //Centrar el frame al executar-se.
        this.setLocationRelativeTo(null);

        //Missatge d'error en cas de que no hi hagin TAGS per mostrar.
        int contTags = getNumeroTags();
        if (contTags == 0) {
            missatgeElimina("No hi han categories per eliminar!", "GestioCategories - Elimina");
        }
    }

    //Metode per crear missatges/alertes.
    public void missatgeElimina(String missatge, String titol) {
        JOptionPane.showMessageDialog(null, missatge, titol, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inici = new javax.swing.JButton();
        Consulta = new javax.swing.JButton();
        Alta = new javax.swing.JButton();
        Modifica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idEliminaFiltre = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        Info1 = new javax.swing.JLabel();
        elimina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        info1 = new javax.swing.JLabel();
        TextField_Filter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestioCategories - Elimina");
        setPreferredSize(new java.awt.Dimension(550, 450));

        Inici.setText("INICI");
        Inici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciActionPerformed(evt);
            }
        });

        Consulta.setText("CONSULTA");
        Consulta.setActionCommand("");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });

        Alta.setText("ALTA");
        Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaActionPerformed(evt);
            }
        });

        Modifica.setText("MODIFICA");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        jLabel1.setText("Quina categoria vols ELIMINAR, introdueix la ID:");

        idEliminaFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEliminaFiltreActionPerformed(evt);
            }
        });

        confirma.setText("CONFIRMA");
        confirma.setActionCommand("");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        cancela.setText("CANCELA");
        cancela.setActionCommand("");
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        Info1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Info1.setText("ELIMINA LA CATEGORIA");
        Info1.setToolTipText("");
        Info1.setPreferredSize(new java.awt.Dimension(148, 18));

        elimina.setText("ELIMINA");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        info1.setText("Filtre de categories:");
        info1.setToolTipText("");

        TextField_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_FilterActionPerformed(evt);
            }
        });
        TextField_Filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_FilterKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Inici, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modifica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idEliminaFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(info1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(confirma, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consulta)
                    .addComponent(Alta)
                    .addComponent(Inici)
                    .addComponent(Modifica)
                    .addComponent(elimina))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEliminaFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancela)
                    .addComponent(confirma))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEliminaFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEliminaFiltreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEliminaFiltreActionPerformed

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        
        //CONTROL DE ERRORS / EXCEPCIONS
        try {
        
            int contTags = getNumeroTags();
            int numIntroduit = getFiltre();

            //Condicio 1
            if (contTags == 0) {
                //ALERTA: No hi han categories per eliminar.
                missatgeElimina("No hi han categories per eliminar.", "GestioCategories - Elimina");

            //Condicio 2
            } else if (numIntroduit > contTags - 1) {
                //ALERTA: La categoria que vols eliminar no existeix.
                missatgeElimina("La categoria que vols eliminar no existeix.", "GestioCategories - Elimina");

            //Condicio final ELIMINAR
            } else {

                //CRIDA DE Moduls.ModulBaixa.EliminaTags i eliminem una Categoria.
                Moduls.ModulBaixa.EliminaTags(numIntroduit);

                if (numIntroduit >= 0) {
                    Categoria.NUMERO_TAG--;
                    Categoria.nextId--;
                    //ALERTA: La categoria s'ha eliminat correctament.
                    missatgeElimina("La categoria s'ha eliminat correctament.", "GestioCategories - Elimina");
                }
            }

            TagsConsulta enrere = new TagsConsulta();
            enrere.setVisible(true);
            dispose();
            
        //CONTROL DE ERRORS / EXCEPCIONS
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Introdueix correctament la ID per ELMINAR.");
        }
        
    }//GEN-LAST:event_confirmaActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        // Tornem a la finestra principal
        TagsInici BOTOinici = new TagsInici(TagsInici.li);
        BOTOinici.setVisible(true);            //la fem visible
        dispose();                             //eliminem la finestra actual
    }//GEN-LAST:event_cancelaActionPerformed

    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaActionPerformed
        /****************************************/
        // Anem a la finestra de modificar
        TagsModificaFiltre BOTOmodifica = new TagsModificaFiltre();
        BOTOmodifica.setVisible(true);       //la fem visible
        dispose();                           //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_ModificaActionPerformed

    private void AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaActionPerformed
        /****************************************/
        // Anem a la finestra d'alta
        TagsAlta BOTOalta = new TagsAlta();
        BOTOalta.setVisible(true);       //la fem visible
        dispose();                       //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_AltaActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        /****************************************/
        // Anem a la finestra de consulta
        TagsConsulta BOTOconsulta = new TagsConsulta();
        BOTOconsulta.setVisible(true);       //la fem visible
        dispose();                           //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_ConsultaActionPerformed

    private void IniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciActionPerformed
        /****************************************/
        // Tornem a la finestra principal
        TagsInici BOTOinici = new TagsInici(TagsInici.li);
        BOTOinici.setVisible(true);            //la fem visible
        dispose();                             //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_IniciActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        TagsElimina elimina = new TagsElimina();
        elimina.setVisible(true);            //la fem visible
        dispose();
    }//GEN-LAST:event_eliminaActionPerformed

    private void TextField_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_FilterActionPerformed

    }//GEN-LAST:event_TextField_FilterActionPerformed

    private void TextField_FilterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_FilterKeyTyped
        consulta(TextField_Filter.getText());
    }//GEN-LAST:event_TextField_FilterKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TagsElimina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TagsElimina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TagsElimina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TagsElimina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TagsElimina().setVisible(true);
            }
        });
    }

    
    // METODES
    public void consulta(String filter) {

        Object columnNames[] = {"ID", "Nom", "Descripcio"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        ListIterator tagIter = LlistaCategories.ArrayTags.listIterator();

        while (tagIter.hasNext()) {
            Categoria e = LlistaCategories.ArrayTags.get(tagIter.nextIndex());

            String x = Categoria.toString(e);

            if (x.toLowerCase().contains(filter.toLowerCase())) {

                Object rowData[] = {e.getId_tag(), e.getName(), e.getDesc()};
                model.addRow(rowData);

            }
            tagIter.next();
        }
        jTable1.setModel(model);

    }

    // Plena la taula amb les incidències de l'array
    public void emplenarTaula() {
        
       
        Object columnNames[] = {"ID", "Nom", "Descripcio"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        ListIterator tagIter = LlistaCategories.ArrayTags.listIterator();
        
        while (tagIter.hasNext()) {
            Categoria e = LlistaCategories.ArrayTags.get(tagIter.nextIndex());
                Object rowData[] = {e.getId_tag(), e.getName(), e.getDesc()};
                model.addRow(rowData);
            tagIter.next();
        }
        
        
        jTable1.setModel(model);
    }
    
    
    //Metode que retorna una ID.
    public int getFiltre() {
        return Integer.parseInt(idEliminaFiltre.getText());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alta;
    private javax.swing.JButton Consulta;
    private javax.swing.JLabel Info1;
    private javax.swing.JButton Inici;
    private javax.swing.JButton Modifica;
    private javax.swing.JTextField TextField_Filter;
    private javax.swing.JButton cancela;
    private javax.swing.JButton confirma;
    private javax.swing.JButton elimina;
    private javax.swing.JTextField idEliminaFiltre;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
