package JFrame;

import Classes.*;
import Moduls.*;
import javax.swing.JOptionPane;


/**
 * 
 * Programa per gestionar les categories
 * 04/02/2020
 * @author svyatossemenyuk
 * GRUP 1: Xavi Naves - Xavier Romeu - Javier Perez - Svyatos Semenyuk
 * @version v5 (versio final, amb CRUD, CSV import/export, Logs, ArrayList tot)
 */

public class TagsAlta extends javax.swing.JFrame {

    /**
     * Creates new form Alta
     */
    public TagsAlta() {
        
        initComponents();
        //Centrar el frame al executar-se.
        this.setLocationRelativeTo(null);
        
        //Numero de ID de la seguent categoria
        nextTaag.setText(String.valueOf(Categoria.getNumeroTags()));
        
    }
    
    //Metode per crear missatges/alertes.
    public void missatgeAlta1 (String missatge, String titol){
        JOptionPane.showMessageDialog(null, missatge, titol, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info1 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        CampNom = new javax.swing.JTextField();
        CampDesc = new javax.swing.JTextField();
        nextTaag = new javax.swing.JLabel();
        confirma = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        Inici = new javax.swing.JButton();
        Consulta = new javax.swing.JButton();
        Alta = new javax.swing.JButton();
        Modifica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        elimina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestioCategories - Alta");
        setPreferredSize(new java.awt.Dimension(551, 451));

        Info1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Info1.setText("ALTA DE CATEGORIES");
        Info1.setToolTipText("");
        Info1.setPreferredSize(new java.awt.Dimension(148, 18));

        Info2.setText("CATEGORIA:");
        Info2.setToolTipText("");

        Info3.setText("DESCRIPCIO:");
        Info3.setToolTipText("");

        CampNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampNomActionPerformed(evt);
            }
        });

        CampDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampDescActionPerformed(evt);
            }
        });

        nextTaag.setToolTipText("");

        confirma.setText("CONFIRMA");
        confirma.setActionCommand("");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        cancela.setText("CANCELA");
        cancela.setActionCommand("");
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        Inici.setText("INICI");
        Inici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciActionPerformed(evt);
            }
        });

        Consulta.setText("CONSULTA");
        Consulta.setActionCommand("");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });

        Alta.setText("ALTA");
        Alta.setSelected(true);
        Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaActionPerformed(evt);
            }
        });

        Modifica.setText("MODIFICA");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        elimina.setText("ELIMINA");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampNom)
                            .addComponent(Info2)
                            .addComponent(Info3)
                            .addComponent(CampDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextTaag, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Inici, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modifica)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirma, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inici)
                    .addComponent(Consulta)
                    .addComponent(Alta)
                    .addComponent(Modifica)
                    .addComponent(elimina))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Info2))
                    .addComponent(nextTaag, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Info3)
                .addGap(7, 7, 7)
                .addComponent(CampDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancela)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampNomActionPerformed

    private void CampDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampDescActionPerformed

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        
        //Alta d'una categoria
        Moduls.ModulAlta.AltaTags(LlistaCategories.ArrayTags, CampNom.getText(), CampDesc.getText());
        
        //Missatges d'informacio
        missatgeAlta1("S'ha enregistrat una categoria", "GestioCategories - Alta");

        //Tornariem a Alta.        
        TagsAlta alta = new TagsAlta();
        alta.setVisible(true);
        dispose();   
    }//GEN-LAST:event_confirmaActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        // Tornem a la finestra principal
        TagsInici BOTOinici = new TagsInici(TagsInici.li);
        BOTOinici.setVisible(true);            //la fem visible
        dispose();                             //eliminem la finestra actual
    }//GEN-LAST:event_cancelaActionPerformed

    private void IniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciActionPerformed
        /****************************************/
        // Tornem a la finestra principal
        TagsInici BOTOinici = new TagsInici(TagsInici.li);
        BOTOinici.setVisible(true);            //la fem visible
        dispose();                             //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_IniciActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        /****************************************/
        // Anem a la finestra de consulta
        TagsConsulta BOTOconsulta = new TagsConsulta();
        BOTOconsulta.setVisible(true);       //la fem visible
        dispose();                           //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_ConsultaActionPerformed

    private void AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaActionPerformed
        /****************************************/
        // Anem a la finestra d'alta
        TagsAlta BOTOalta = new TagsAlta();
        BOTOalta.setVisible(true);       //la fem visible
        dispose();                       //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_AltaActionPerformed

    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaActionPerformed
        /****************************************/
        // Anem a la finestra de modificar
        TagsModificaFiltre BOTOmodifica = new TagsModificaFiltre();
        BOTOmodifica.setVisible(true);       //la fem visible
        dispose();                           //eliminem la finestra actual
        /****************************************/
    }//GEN-LAST:event_ModificaActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        TagsElimina elimina = new TagsElimina();
        elimina.setVisible(true);            //la fem visible
        dispose();  
    }//GEN-LAST:event_eliminaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TagsAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TagsAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TagsAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TagsAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TagsAlta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alta;
    private javax.swing.JTextField CampDesc;
    private javax.swing.JTextField CampNom;
    private javax.swing.JButton Consulta;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JButton Inici;
    private javax.swing.JButton Modifica;
    private javax.swing.JButton cancela;
    private javax.swing.JButton confirma;
    private javax.swing.JButton elimina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nextTaag;
    // End of variables declaration//GEN-END:variables
}
